version: '2'
services:
    frontend:
        hostname: vue-express-boilerplate
        working_dir: /usr/src/app
        build:
            context: ./
        ports:
            - "4000:4000"
        restart: always
        volumes:
          - "./:/usr/src/app"
